export const GET_SONGS_START = 'GET_SONGS_START';
export const GET_SONGS_SUCCESS = 'GET_SONGS_SUCCESS';
export const GET_SONGS_FAIL = 'GET_SONGS_FAIL';

export const GET_SEARCH_SONGS_START = 'GET_SEARCH_SONGS_START';
export const GET_SEARCH_SONGS_SUCCESS = 'GET_SEARCH_SONGS_SUCCESS';
export const GET_SEARCH_SONGS_FAIL = 'GET_SEARCH_SONGS_FAIL';

export const EMPTY_SEARCH_ACTIVE = 'EMPTY_SEARCH_ACTIVE';

